@pizzaUrl = http://localhost:3000/pizzas

### Create a pizza
POST {{pizzaUrl}}
Content-Type: application/json

{
    "title":"Magic Green",
    "content":"Epinards, Brocolis, Olives vertes, Basilic"
}

### Read all pizzas with File variable
GET {{pizzaUrl}}

### Read all pizzas sorted by title (ascending)
GET {{pizzaUrl}}/?order=+title

### Read all pizzas sorted by title (descending)
GET {{pizzaUrl}}/?order=-title

### Delete pizza identified by 2
DELETE {{pizzaUrl}}/2

### Update the pizza identified by 6
PATCH {{pizzaUrl}}/6
Content-Type: application/json

{
    "title":"Magic Green 2"
}



